### ISSUE TITLE
Panel menu box-shadows

### ISSUE THREAD

**Issue by FistMeNaruto** [andreisergiu98/arc-flatabulous-theme#16]
- [x] I read the list above.
- [x] I read the README.
- [x] I checked if my issue isn't duplicated.

**Details:**

- Distribution: Arch Linux
- Desktop environment: Gnome
- GTK+ 3 version: 	3.20.8-1
- Arc version (commit): 4f8bf3a

Weird box shadows, trying to find a solution.

![screenshot from 2016-08-11 00-04-06](https://cloud.githubusercontent.com/assets/13431677/17571131/9bc37cf8-5f57-11e6-829b-b823db00cb19.png)
![screenshot from 2016-08-11 00-04-28](https://cloud.githubusercontent.com/assets/13431677/17571409/bb4ce59a-5f58-11e6-8990-26adfa708f06.png)
![screenshot from 2016-08-11 00-04-41](https://cloud.githubusercontent.com/assets/13431677/17571412/bdb800d0-5f58-11e6-8899-e96ed111e5f2.png)

**Comment by andreisergiu98** [comment]
I'm sorry it took so long to respond, i was pretty busy. I tried to reproduce your bug without success, but i merged with the last commits of horst's so your bug might or might not be fixed. Can you check it out? Thanks ;)

**Comment by FistMeNaruto** [comment]
Problem still persists, might not be the theme's fault, I'll see if i'll be able to do anything. Thanks :)

**Comment by FistMeNaruto** [comment]
Apparently https://github.com/nana-4/Flat-Plat gdm theme was the cause. Closing the issue.
