### ISSUE TITLE
Separators in Menus takes too much space 

### ISSUE THREAD

**Issue by didli** [andreisergiu98/arc-flatabulous-theme#18]
This is more as a request than a bug : in Fedora 24 x64 with Xfce, latest git, separators within menus takes too much space (scaling up the menus a bit too much in comparison to others themes). 
Either way, great theme ! A must-have to gives a kind of "material design" style to our desktops. Thank you !

**Comment by andreisergiu98** [comment]
Sry for the late reply, I will try to do something next week.

**Comment by andreisergiu98** [comment]
Is it ok now?

**Comment by didli** [comment]
Hi ! It's way better. Especially on context menus from the desktop (right click menu in Desktop is fine now). Context menus from panels or the bin, or panel elements (orage plugin for example) are still a little off.
But honestly it's kind of a detail, it's ok to leave it like this I think. 
Thanks !
