### ISSUE TITLE
Metacity theme doesn't change minimize and maximize buttons.

### ISSUE THREAD

**Issue by MrGreenTea** [andreisergiu98/arc-flatabulous-theme#19]
First, thanks for your great theme. The combination looks really great. 
Because only the close button is themed in the metacity theme, some apps (chrome, gimp, atom.io ...) have different window buttons than most other apps. I am looking into fixing it and If I manage to that, I'll create a PR.

**Comment by andreisergiu98** [comment]
Ok thanks!

**Comment by MrGreenTea** [comment]
I kinda have it now, but the colors are a bit different. I think it has to do with the colorization of the grey icons in the metacity themes. I don't know enough about colors or how metacity applies the colorization color to know how to extract the correct colors, but I am looking in to it.

**Comment by MrGreenTea** [comment]
Why don't you/we use the png files provided by Flatabulous?

**Comment by MrGreenTea** [comment]
Now it looks great, I just used the icons provided by flatabulous.

**Comment by andreisergiu98** [comment]
Thanks!
