### ISSUE TITLE
File open dialog: sidebar in "dark" version is meh

### ISSUE THREAD

**Issue by malyavkin** [andreisergiu98/arc-flatabulous-theme#2]
![screenshot from 2016-04-12 00-26-33](https://cloud.githubusercontent.com/assets/4255635/14442995/46e12468-0045-11e6-98e8-ee2905d6bba6.png)

Seriously though, there's a lot of themes with this exact issue

**Comment by andreisergiu98** [comment]
I think it is fixed by horst, i tried to reproduce the bug without success.
