### ISSUE TITLE
Reduce headerbar/titlebar buttons' horizontal padding

### ISSUE THREAD

**Issue by dasnoopy** [andreisergiu98/arc-flatabulous-theme#22]
Should be possible reduce horizontal padding for headerbar and titlebar buttons?

...something like this, just to be clear :

![padding](https://cloud.githubusercontent.com/assets/296922/20049488/a49aebca-a4c3-11e6-9f89-396ab0d62e8e.png)

Regards
Andrea

- Archlinux 64bit
- Gnome 3.22.1
- gtk-arc-flatabulous-theme-git-668.bb41d28
- GTK+ 3 version3.22.2
  - Murrine engine version: gtk-engine-murrine-0.98.2
  - `gnome-themes-standard` version: gnome-themes-standard-3.22.2
- Installation method : AUR package

**Comment by andreisergiu98** [comment]
Sry it took so long to respond. Try to put the following in `~/.config/gtk-3.0/gtk.css` (create the file if it does not exist).

`headerbar button{
	padding: 0px;
	min-width: 0px;
}
`

**Comment by dasnoopy** [comment]
tip  works  fine... tnks a lot
Andrea

**Comment by iwantedsupernovabutitwastaken** [comment]
Sorry to be bumping this old thread.

Any tips on changing the color of the theme? I'd like to change the solarized type blue to a shade of gray. Also i'd like to change window button colors. To illustrate better what i mean take a look at this.

![screenshot from 2018-01-24 12-04-23](https://user-images.githubusercontent.com/33897651/35329347-da545834-00ff-11e8-8b19-7a45009bf3aa.png)
