### ISSUE TITLE
Cinnamon: Arc-Flatabulous renders minimize button a darker shade of grey

### ISSUE THREAD

**Issue by nick-s-b** [andreisergiu98/arc-flatabulous-theme#24]
I'm running Arch Linux with Cinnamon 3.2.7 DE. I've installed though AUR: 
`aur/gtk-arc-flatabulous-theme-git 586.f827ce3-1 [installed: 668.bb41d28-1]`
and judging by the official git commit code, that is the latest version.

The issue is a minor, but an annoying one. When a window is in the background, Close and Maximize window widgets are of the same shade of grey yet the Minimize button is slightly darker. I have no idea why this happens and I've looked at the files in `/usr/share/themes/Arc-Flatabulous` and can't figure out which of them is the culprit.

Here's what it looks like:
![https://i.imgur.com/KbcbYY5.png](https://i.imgur.com/KbcbYY5.png)
Close/Minimize/Maximize... and Minimize is darker. No idea why.

Can someone help? Thanks :)

**Comment by andreisergiu98** [comment]
I merged horst's latest commits, and he added support for cinnamon 3.2, i don't think it helps tho. I'll check it out after i change my internet connection with a faster one.

**Comment by nick-s-b** [comment]
All right, I had some free time today and decided to take a second look at this. The issue is 
`Arc-Flatabulous/metacity-1/minimize_unfocused.png` image. For some reason, someone made it darker. If you replace it with `Arc-Flatabulous/metacity-1/maximize_unfocused.png`, all of the window decorations will look right and the same. I suggest you just get rid of the old one.

Also, the spacing between the window widgets is all wrong. This is due to this line
https://github.com/andreisergiu98/arc-flatabulous-theme/blob/a611c1e7960f36fc623b20a6c3747c7111dd889c/common/metacity-1/metacity-theme-3.xml#L32

I've changed it to `<distance name="button_width" value="22"/>` and now it's perfect and exactly the same as macOS.

Also, files `metacity-theme-1.xml` and `metacity-theme-2.xml` are superflous since DE only picks the one with the largest number... in this case `metacity-theme-3.xml`

The result is something that looks great:

![https://i.imgur.com/mtGyFhT.jpg](https://i.imgur.com/mtGyFhT.jpg)
