### ISSUE TITLE
Buttons not proper on some Apps

### ISSUE THREAD

**Issue by phoenisx** [andreisergiu98/arc-flatabulous-theme#25]
Some Applications like Audacity, Gimp, Eclipse etc. displays fine, but the texture of their buttons are Hard Squares and really look weird..

Is their a solution to change buttons to look like the proper theme... As shown below

> This is the Improper App, with Awkward Buttons....

![improper](https://cloud.githubusercontent.com/assets/11786283/22319848/88720f6e-e3ac-11e6-9f09-0388361dbbbc.png)

> How this app looks like in default Ambiance Theme in Ubuntu...

![ambiance](https://cloud.githubusercontent.com/assets/11786283/22319939/9bf860be-e3ad-11e6-9d7e-a4fdca397633.png)

> This is a proper App, with nice Twitter Bootstrap kind of look in buttons...

![proper](https://cloud.githubusercontent.com/assets/11786283/22319866/cb61307a-e3ac-11e6-9371-49301d51ea8d.png)

I hope this issue is clear... If possible, is their a way to Tweak this error...

Thanks

**Comment by Jibehh** [comment]
Did you solve this? I've got the same problem...
