### ISSUE TITLE
No depressed icon for minimize button 

### ISSUE THREAD

**Issue by camwright** [andreisergiu98/arc-flatabulous-theme#28]
The minimize button doesn't differentiate when it is pressed from when it is hovered over, as the close and maximize buttons do.
![close hover](https://cloud.githubusercontent.com/assets/2886470/25879048/072de3ae-34e4-11e7-87a7-ea64fec4e63a.png)
![close pressed](https://cloud.githubusercontent.com/assets/2886470/25879002/aadae066-34e3-11e7-96f8-5930a47584d5.png)
![minimized hover/pressed](https://cloud.githubusercontent.com/assets/2886470/25879007/b0e989c6-34e3-11e7-824f-d8e7c21c6832.png)

### Details
- Fedora 25
- Gnome 3.22.2
- Commit a611c1e
- GTK+ 3 version:
  - Murrine engine version: 0.98.2-10
  - `gnome-themes-standard` version: 3.22.3-1
- Installation method: Source

**Comment by andreisergiu98** [comment]
There is a difference between them, tho it's subtle.

See here:
![](https://i.imgur.com/IMc6hsr.png)

I can change that in the future, to be more visible, but not now.
