### ISSUE TITLE
ibus candidate ui is still transparent with --disable-transparency parameter

### ISSUE THREAD

**Issue by kevinhwang91** [andreisergiu98/arc-flatabulous-theme#42]
I'm using Arc-Flatabulous-Dark-solid theme. It seems only the ibus candidate ui is transparent，others ui is solid perfectly.

env:
gnome version: 3.32.2
arc-flatabulous-theme: lasted version

![2019-05-30_11-37](https://user-images.githubusercontent.com/17562139/58606740-5c4e7e80-82cf-11e9-81b7-1cf9a478e3c9.png)

**Comment by kawoki** [comment]
I'm having also a problem with Arc-Flatabulous-solid

![Screenshot from 2019-08-12 00-26-54](https://user-images.githubusercontent.com/12818739/62836646-edf74680-bc97-11e9-8c2a-da1e7df331c1.png)

**Comment by kevinhwang91** [comment]
> I'm having also a problem with Arc-Flatabulous-solid
> 
> GNOME version: 3.32.1
> Arc-Flatabulous-Theme: Latest version
> 
> ![Screenshot from 2019-08-12 00-26-54](https://user-images.githubusercontent.com/12818739/62836646-edf74680-bc97-11e9-8c2a-da1e7df331c1.png)

In my environment, either the light or the dark theme with --disable-transparency parameter works fine in the file manager(nautilus). I suggest you make clean or git clone the repository(not git reset --hard, because of the .gitignore include many files), and then execute autogen.sh --disable-transparency again. Maybe work for you.

**Comment by kevinhwang91** [comment]
I found some ui also not work perfectly. such as
![2019-08-12_11-40](https://user-images.githubusercontent.com/17562139/62844796-39d8d880-bcf6-11e9-85b2-c0b74dd77654.png)

**Comment by kawoki** [comment]
Still the same. Nevermind :) This may be not related to the issue but how to remove the arrows from exporer breadcrumbs (beside the home and the downloads)?

![image](https://user-images.githubusercontent.com/12818739/62913446-a3bcb500-bdbe-11e9-95b6-476cd05bda6d.png)

**Comment by kevinhwang91** [comment]
I manually edit the css(such as candidate-popup-boxpointer) of the gnome-shell.css file but not the build scripts, and then it works perfect as I expect.

The scripts are so complicated for me to edit. Can someone do that?
