### ISSUE TITLE
yosemite style buttons 

### ISSUE THREAD

**Issue by tristan-k** [andreisergiu98/arc-flatabulous-theme#5]
Maybe it's just me, but the window buttons are not like in the preview of the [README.md](https://camo.githubusercontent.com/dc62b4c6643a951d28c5f0e428a4bdb3c5efa248/687474703a2f2f692e696d6775722e636f6d2f73474f454b364c2e706e67). 

I compiled with `./autogen.sh --prefix=/usr --disable-cinnamon --disable-gnome-shell --disable-metacity --disable-unity ` for Xubuntu 16.04.

![bildschirmfoto_2016-05-02_14-59-14](https://cloud.githubusercontent.com/assets/732025/14954936/8709ef16-1076-11e6-869b-bd31fb1cbd20.png)

```
WM: Xfwm4
WM Theme: Arc-Flataburous
GTK Theme: Arc-Flataburous [GTK2]
Icon Theme: Numix-Circle
```

**Comment by andreisergiu98** [comment]
I did not change the buttons for xfwm4, so that's why you have stock arc buttons. Unfortunately i have some serious exams coming, so i don't have time to change them.

**Comment by Serubin** [comment]
Just wanted to bump this for when you have time again.
Thanks!
