### ISSUE TITLE
Small button size and flickering on inactive windows.

### ISSUE THREAD

**Issue by StefanescuCristian** [andreisergiu98/arc-flatabulous-theme#6]
- Distribution: Ubuntu 16.04
- Desktop environment: Unity
- GTK+ 3 version: 3.18.9-1ubuntu3
- Arc version (commit): master

Hello,
The windows controls on Ubuntu 16.04 the buttons are a little smaller than I expected.
Also, when hovering over a inactive window, some flickering occurs.
If the size of the buttons is not a bug, but a feature, then I understand, but the I think flickering should not be there.

I've attached a zip with a recording of my screen. If there's anyway I can help, don't esitate to contact me.

[flatabulos.ogv.zip](https://github.com/andreisergiu98/arc-flatabulous-theme/files/333836/flatabulos.ogv.zip)

Thanks.

**Comment by andreisergiu98** [comment]
Yep both the size and the flickering are bugs, i think i messed up something. I can't check them in the next 3 weeks, i got some serious exams, so you'll have to wait. In the mean time you can try the original themes: arc or flatabulous.

**Comment by StefanescuCristian** [comment]
Can I help you somehow?
Or can you tell me where I should look so I can try to fix it?

**Comment by andreisergiu98** [comment]
You can look in common/unity, maybe I forgot to change some buttons.
