### ISSUE TITLE
just a copy of arc

### ISSUE THREAD

**Issue by Pival81** [andreisergiu98/arc-flatabulous-theme#8]
that's just a copy of arc, there is no flataboulous in here.
edit: oh, ok, didn't read about gtk 3.20

**Comment by andreisergiu98** [comment]
Can you give more details? is it not working for you?

**Comment by andreisergiu98** [comment]
I gave you 2 days to think of something smart. If you find out what you want, open another issue. Remember think before you type, and please read the [README](https://github.com/andreisergiu98/arc-flatabulous-theme/blob/master/README.md ). Don't spam my fork. ;)
